---
- name: Launch backend app container
  community.docker.docker_container:
    name: backend
    image: "{{ DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest"
    pull: true 
    state: started
    restart_policy: unless-stopped
    networks:
      - name: my-network
    env:
      DB_HOST: "{{ DB_HOST }}"
      DB_NAME: "{{ POSTGRES_DB }}"
      DB_USER: "{{ POSTGRES_USER }}"
      DB_PASSWORD: "{{ POSTGRES_PASSWORD }}"