---
- name: Launch database container
  community.docker.docker_container:
    name: database
    image: "{{ DOCKERHUB_USERNAME }}/tp-devops-database:latest"
    state: started
    restart_policy: unless-stopped
    pull: true 
    networks:
      - name: my-network
    env:
      POSTGRES_DB: "{{ POSTGRES_DB}}"
      POSTGRES_USER: "{{ POSTGRES_USER }}"
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"