all:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: /Users/harshakhiyani/My_Stuff/Study/Newkey/id_rsa
    ansible_python_interpreter: /opt/docker_venv/bin/python
  children:
    prod:
      hosts:
        jatin.khiyani.takima.school:
