name: Build and Push Docker Images

on:
  workflow_run:
    workflows: ["CI devops 2025"]
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    environment: Docker-env

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push database image
        uses: docker/build-push-action@v6
        with:
          context: ./TP-1/database
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: true

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./TP-1/Backend/Springboot
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: true

      - name: Build and push httpd image
        uses: docker/build-push-action@v6
        with:
          context: ./TP-1/httpd
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: true
  
  
  deploy-application:
    runs-on: ubuntu-24.04
    needs: build-and-push-docker-image
    environment: Docker-env

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          ansible-galaxy collection install community.docker

      - name: Deploy using Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          ansible-playbook -i my-project/ansible/inventories/setup.yml \
            my-project/ansible/playbook.yml \
            --private-key=private_key.pem \
            -u admin \
            -e "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} \
                POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
                POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
                POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
                DB_HOST=${{ secrets.DB_HOST }} \
                BACKEND_HOST=${{ secrets.BACKEND_HOST }}"          