name: CI devops 2025
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: main
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    environment: Docker-env
    steps:
      #checkout your github code using actions/checkout@v4
      - uses: actions/checkout@v4

      #do the same with another action (actions/setup-java@v4) that enable to setup jdk 21
      - name: Set up JDK 21
        #TODO
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      #finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean verify
        working-directory: TP-1/Backend/Springboot

  Sonar:
    needs: test-backend
    runs-on: ubuntu-24.04
    environment: Docker-env

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        #TODO
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

        # Sonar Analysis (Comment added to push)
      - name: SonarCloud
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=${{ secrets.PROJECT_KEY }} -Dsonar.organization=${{ secrets.ORGANIZATION_KEY }} -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        working-directory: TP-1/Backend/Springboot

  build-and-push-docker-image:
    needs: Sonar
    runs-on: ubuntu-24.04
    environment: Docker-env

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push database image
        uses: docker/build-push-action@v6
        with:
          context: ./TP-1/database
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./TP-1/Backend/Springboot
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push httpd image
        uses: docker/build-push-action@v6
        with:
          context: ./TP-1/httpd
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}
